export const dictionary:Array<any> = [
  {
    dictId: "cmbbc4omffl4bn5l69fg",
    parent: "0",
    label: "性别",
    value: "sex",
    createdAt: null,
    updatedAt: null,
    remark: "性别",
    children: [
      {
        dictId: "cmbc04gmffl4191uplu0",
        parent: "cmbbc4omffl4bn5l69fg",
        label: "保密",
        value: "2",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc030mffl4191upltg",
        parent: "cmbbc4omffl4bn5l69fg",
        label: "男",
        value: "1",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc01omffl4191uplt0",
        parent: "cmbbc4omffl4bn5l69fg",
        label: "女",
        value: "0",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
    ],
  },
  {
    dictId: "cmpghk05lm7kpt74ppt0",
    parent: "0",
    label: "菜单类型",
    value: "menuType",
    createdAt: null,
    updatedAt: "2024-01-26 16:54:42",
    remark: "菜单类型，目录，菜单，按钮",
    children: [
      {
        dictId: "cmpgi9o5lm7kpt74ppug",
        parent: "cmpghk05lm7kpt74ppt0",
        label: "按钮",
        value: "button",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmpgi785lm7kpt74ppu0",
        parent: "cmpghk05lm7kpt74ppt0",
        label: "菜单",
        value: "menu",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmpgi485lm7kpt74pptg",
        parent: "cmpghk05lm7kpt74ppt0",
        label: "目录",
        value: "directory",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
    ],
  },
  {
    dictId: "cmbc6igmffl4191upm5g",
    parent: "0",
    label: "用户类型",
    value: "userType",
    createdAt: null,
    updatedAt: null,
    remark: "区分微信登陆或者手机注册等用户来源",
    children: [
      {
        dictId: "cmbc6s0mffl4191upm6g",
        parent: "cmbc6igmffl4191upm5g",
        label: "默认",
        value: "default",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc6o0mffl4191upm60",
        parent: "cmbc6igmffl4191upm5g",
        label: "微信",
        value: "wechat",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
    ],
  },
  {
    dictId: "cmqsrejdervjk5pcghg0",
    parent: "0",
    label: "菜单大类",
    value: "menuCategory",
    createdAt: "2024-01-28 11:44:58",
    updatedAt: null,
    remark: "路由菜单，目录菜单等",
    children: [
      {
        dictId: "cmqsrqbdervjk5pcghh0",
        parent: "cmqsrejdervjk5pcghg0",
        label: "文档",
        value: "note",
        createdAt: "2024-01-28 11:45:46",
        updatedAt: null,
        remark: "文档菜单",
        children: null,
      },
      {
        dictId: "cmqsrl3dervjk5pcghgg",
        parent: "cmqsrejdervjk5pcghg0",
        label: "路由",
        value: "routes",
        createdAt: "2024-01-28 11:45:25",
        updatedAt: null,
        remark: "路由菜单",
        children: null,
      },
    ],
  },
  {
    dictId: "cmv4vq3dervirktgq5n0",
    parent: "0",
    label: "test1123",
    value: "test1123",
    createdAt: "2024-02-03 22:38:33",
    updatedAt: "2024-02-03 22:38:40",
    remark: "test1123",
    children: [
      {
        dictId: "cmv50qjdervirktgq5ng",
        parent: "cmv4vq3dervirktgq5n0",
        label: "qqq",
        value: "qqq",
        createdAt: "2024-02-03 22:40:42",
        updatedAt: "2024-02-03 22:42:12",
        remark: "qqq",
        children: null,
      },
    ],
  },
  {
    dictId: "cn08srbdervqmt7o7td0",
    parent: "0",
    label: "11",
    value: "1231",
    createdAt: "2024-02-05 15:29:50",
    updatedAt: null,
    remark: "23",
    children: null,
  },
  {
    dictId: "cmbc2j0mffl4191upm0g",
    parent: "0",
    label: "笔记分类",
    value: "noteCategory",
    createdAt: null,
    updatedAt: null,
    remark: "",
    children: [
      {
        dictId: "cmbc3ggmffl4191upm50",
        parent: "cmbc2j0mffl4191upm0g",
        label: "微信",
        value: "wechat",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc39omffl4191upm4g",
        parent: "cmbc2j0mffl4191upm0g",
        label: "linux",
        value: "linux",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc37omffl4191upm40",
        parent: "cmbc2j0mffl4191upm0g",
        label: "nginx",
        value: "nginx",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc368mffl4191upm3g",
        parent: "cmbc2j0mffl4191upm0g",
        label: "docker",
        value: "docker",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc30omffl4191upm30",
        parent: "cmbc2j0mffl4191upm0g",
        label: "node",
        value: "node",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc2t0mffl4191upm2g",
        parent: "cmbc2j0mffl4191upm0g",
        label: "golang",
        value: "golang",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc2rgmffl4191upm20",
        parent: "cmbc2j0mffl4191upm0g",
        label: "javascript",
        value: "javascript",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc2q0mffl4191upm1g",
        parent: "cmbc2j0mffl4191upm0g",
        label: "css",
        value: "css",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmbc2o0mffl4191upm10",
        parent: "cmbc2j0mffl4191upm0g",
        label: "html",
        value: "html",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: null,
      },
    ],
  },
  {
    dictId: "cmqsndg5lm7vlg415isg",
    parent: "0",
    label: "是否",
    value: "whether",
    createdAt: "2024-01-28 03:36:23",
    updatedAt: null,
    remark: "是否选项 true false",
    children: [
      {
        dictId: "cmqsns85lm7vlg415itg",
        parent: "cmqsndg5lm7vlg415isg",
        label: "否",
        value: "0",
        createdAt: "2024-01-28 03:37:22",
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmqsni05lm7vlg415it0",
        parent: "cmqsndg5lm7vlg415isg",
        label: "是",
        value: "1",
        createdAt: "2024-01-28 03:36:41",
        updatedAt: "2024-01-28 11:43:14",
        remark: "",
        children: null,
      },
    ],
  },
  {
    dictId: "cmqtdsrdervjk5pcghhg",
    parent: "0",
    label: "数据类型",
    value: "typeof",
    createdAt: "2024-01-28 12:24:20",
    updatedAt: null,
    remark: "javascript数据类型",
    children: [
      {
        dictId: "cmqtedrdervjk5pcghk0",
        parent: "cmqtdsrdervjk5pcghhg",
        label: "对象",
        value: "object",
        createdAt: "2024-01-28 12:25:28",
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmqtebbdervjk5pcghjg",
        parent: "cmqtdsrdervjk5pcghhg",
        label: "数组",
        value: "array",
        createdAt: "2024-01-28 12:25:18",
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmqte8jdervjk5pcghj0",
        parent: "cmqtdsrdervjk5pcghhg",
        label: "布尔",
        value: "boolean",
        createdAt: "2024-01-28 12:25:07",
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmqte53dervjk5pcghig",
        parent: "cmqtdsrdervjk5pcghhg",
        label: "数字",
        value: "number",
        createdAt: "2024-01-28 12:24:52",
        updatedAt: null,
        remark: "",
        children: null,
      },
      {
        dictId: "cmqte23dervjk5pcghi0",
        parent: "cmqtdsrdervjk5pcghhg",
        label: "字符串",
        value: "string",
        createdAt: "2024-01-28 12:24:41",
        updatedAt: null,
        remark: "",
        children: null,
      },
    ],
  },
  {
    value: "all",
    label: "all",
    children: [
      {
        dictId: "0",
        parent: "",
        label: "root",
        value: "0",
        createdAt: null,
        updatedAt: null,
        remark: "根节点",
        children: [
          {
            dictId: "cmbbc4omffl4bn5l69fg",
            parent: "0",
            label: "性别",
            value: "sex",
            createdAt: null,
            updatedAt: null,
            remark: "性别",
            children: [
              {
                dictId: "cmbc04gmffl4191uplu0",
                parent: "cmbbc4omffl4bn5l69fg",
                label: "保密",
                value: "2",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc030mffl4191upltg",
                parent: "cmbbc4omffl4bn5l69fg",
                label: "男",
                value: "1",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc01omffl4191uplt0",
                parent: "cmbbc4omffl4bn5l69fg",
                label: "女",
                value: "0",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
            ],
          },
          {
            dictId: "cmpghk05lm7kpt74ppt0",
            parent: "0",
            label: "菜单类型",
            value: "menuType",
            createdAt: null,
            updatedAt: "2024-01-26 16:54:42",
            remark: "菜单类型，目录，菜单，按钮",
            children: [
              {
                dictId: "cmpgi9o5lm7kpt74ppug",
                parent: "cmpghk05lm7kpt74ppt0",
                label: "按钮",
                value: "button",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmpgi785lm7kpt74ppu0",
                parent: "cmpghk05lm7kpt74ppt0",
                label: "菜单",
                value: "menu",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmpgi485lm7kpt74pptg",
                parent: "cmpghk05lm7kpt74ppt0",
                label: "目录",
                value: "directory",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
            ],
          },
          {
            dictId: "cmbc6igmffl4191upm5g",
            parent: "0",
            label: "用户类型",
            value: "userType",
            createdAt: null,
            updatedAt: null,
            remark: "区分微信登陆或者手机注册等用户来源",
            children: [
              {
                dictId: "cmbc6s0mffl4191upm6g",
                parent: "cmbc6igmffl4191upm5g",
                label: "默认",
                value: "default",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc6o0mffl4191upm60",
                parent: "cmbc6igmffl4191upm5g",
                label: "微信",
                value: "wechat",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
            ],
          },
          {
            dictId: "cmqsrejdervjk5pcghg0",
            parent: "0",
            label: "菜单大类",
            value: "menuCategory",
            createdAt: "2024-01-28 11:44:58",
            updatedAt: null,
            remark: "路由菜单，目录菜单等",
            children: [
              {
                dictId: "cmqsrqbdervjk5pcghh0",
                parent: "cmqsrejdervjk5pcghg0",
                label: "文档",
                value: "note",
                createdAt: "2024-01-28 11:45:46",
                updatedAt: null,
                remark: "文档菜单",
                children: null,
              },
              {
                dictId: "cmqsrl3dervjk5pcghgg",
                parent: "cmqsrejdervjk5pcghg0",
                label: "路由",
                value: "routes",
                createdAt: "2024-01-28 11:45:25",
                updatedAt: null,
                remark: "路由菜单",
                children: null,
              },
            ],
          },
          {
            dictId: "cmv4vq3dervirktgq5n0",
            parent: "0",
            label: "test1123",
            value: "test1123",
            createdAt: "2024-02-03 22:38:33",
            updatedAt: "2024-02-03 22:38:40",
            remark: "test1123",
            children: [
              {
                dictId: "cmv50qjdervirktgq5ng",
                parent: "cmv4vq3dervirktgq5n0",
                label: "qqq",
                value: "qqq",
                createdAt: "2024-02-03 22:40:42",
                updatedAt: "2024-02-03 22:42:12",
                remark: "qqq",
                children: null,
              },
            ],
          },
          {
            dictId: "cn08srbdervqmt7o7td0",
            parent: "0",
            label: "11",
            value: "1231",
            createdAt: "2024-02-05 15:29:50",
            updatedAt: null,
            remark: "23",
            children: null,
          },
          {
            dictId: "cmbc2j0mffl4191upm0g",
            parent: "0",
            label: "笔记分类",
            value: "noteCategory",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: [
              {
                dictId: "cmbc3ggmffl4191upm50",
                parent: "cmbc2j0mffl4191upm0g",
                label: "微信",
                value: "wechat",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc39omffl4191upm4g",
                parent: "cmbc2j0mffl4191upm0g",
                label: "linux",
                value: "linux",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc37omffl4191upm40",
                parent: "cmbc2j0mffl4191upm0g",
                label: "nginx",
                value: "nginx",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc368mffl4191upm3g",
                parent: "cmbc2j0mffl4191upm0g",
                label: "docker",
                value: "docker",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc30omffl4191upm30",
                parent: "cmbc2j0mffl4191upm0g",
                label: "node",
                value: "node",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc2t0mffl4191upm2g",
                parent: "cmbc2j0mffl4191upm0g",
                label: "golang",
                value: "golang",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc2rgmffl4191upm20",
                parent: "cmbc2j0mffl4191upm0g",
                label: "javascript",
                value: "javascript",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc2q0mffl4191upm1g",
                parent: "cmbc2j0mffl4191upm0g",
                label: "css",
                value: "css",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmbc2o0mffl4191upm10",
                parent: "cmbc2j0mffl4191upm0g",
                label: "html",
                value: "html",
                createdAt: null,
                updatedAt: null,
                remark: "",
                children: null,
              },
            ],
          },
          {
            dictId: "cmqsndg5lm7vlg415isg",
            parent: "0",
            label: "是否",
            value: "whether",
            createdAt: "2024-01-28 03:36:23",
            updatedAt: null,
            remark: "是否选项 true false",
            children: [
              {
                dictId: "cmqsns85lm7vlg415itg",
                parent: "cmqsndg5lm7vlg415isg",
                label: "否",
                value: "0",
                createdAt: "2024-01-28 03:37:22",
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmqsni05lm7vlg415it0",
                parent: "cmqsndg5lm7vlg415isg",
                label: "是",
                value: "1",
                createdAt: "2024-01-28 03:36:41",
                updatedAt: "2024-01-28 11:43:14",
                remark: "",
                children: null,
              },
            ],
          },
          {
            dictId: "cmqtdsrdervjk5pcghhg",
            parent: "0",
            label: "数据类型",
            value: "typeof",
            createdAt: "2024-01-28 12:24:20",
            updatedAt: null,
            remark: "javascript数据类型",
            children: [
              {
                dictId: "cmqtedrdervjk5pcghk0",
                parent: "cmqtdsrdervjk5pcghhg",
                label: "对象",
                value: "object",
                createdAt: "2024-01-28 12:25:28",
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmqtebbdervjk5pcghjg",
                parent: "cmqtdsrdervjk5pcghhg",
                label: "数组",
                value: "array",
                createdAt: "2024-01-28 12:25:18",
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmqte8jdervjk5pcghj0",
                parent: "cmqtdsrdervjk5pcghhg",
                label: "布尔",
                value: "boolean",
                createdAt: "2024-01-28 12:25:07",
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmqte53dervjk5pcghig",
                parent: "cmqtdsrdervjk5pcghhg",
                label: "数字",
                value: "number",
                createdAt: "2024-01-28 12:24:52",
                updatedAt: null,
                remark: "",
                children: null,
              },
              {
                dictId: "cmqte23dervjk5pcghi0",
                parent: "cmqtdsrdervjk5pcghhg",
                label: "字符串",
                value: "string",
                createdAt: "2024-01-28 12:24:41",
                updatedAt: null,
                remark: "",
                children: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    dictId: "0",
    parent: "",
    label: "root",
    value: "0",
    createdAt: null,
    updatedAt: null,
    remark: "根节点",
    children: [
      {
        dictId: "cmbbc4omffl4bn5l69fg",
        parent: "0",
        label: "性别",
        value: "sex",
        createdAt: null,
        updatedAt: null,
        remark: "性别",
        children: [
          {
            dictId: "cmbc04gmffl4191uplu0",
            parent: "cmbbc4omffl4bn5l69fg",
            label: "保密",
            value: "2",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc030mffl4191upltg",
            parent: "cmbbc4omffl4bn5l69fg",
            label: "男",
            value: "1",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc01omffl4191uplt0",
            parent: "cmbbc4omffl4bn5l69fg",
            label: "女",
            value: "0",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
        ],
      },
      {
        dictId: "cmpghk05lm7kpt74ppt0",
        parent: "0",
        label: "菜单类型",
        value: "menuType",
        createdAt: null,
        updatedAt: "2024-01-26 16:54:42",
        remark: "菜单类型，目录，菜单，按钮",
        children: [
          {
            dictId: "cmpgi9o5lm7kpt74ppug",
            parent: "cmpghk05lm7kpt74ppt0",
            label: "按钮",
            value: "button",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmpgi785lm7kpt74ppu0",
            parent: "cmpghk05lm7kpt74ppt0",
            label: "菜单",
            value: "menu",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmpgi485lm7kpt74pptg",
            parent: "cmpghk05lm7kpt74ppt0",
            label: "目录",
            value: "directory",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
        ],
      },
      {
        dictId: "cmbc6igmffl4191upm5g",
        parent: "0",
        label: "用户类型",
        value: "userType",
        createdAt: null,
        updatedAt: null,
        remark: "区分微信登陆或者手机注册等用户来源",
        children: [
          {
            dictId: "cmbc6s0mffl4191upm6g",
            parent: "cmbc6igmffl4191upm5g",
            label: "默认",
            value: "default",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc6o0mffl4191upm60",
            parent: "cmbc6igmffl4191upm5g",
            label: "微信",
            value: "wechat",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
        ],
      },
      {
        dictId: "cmqsrejdervjk5pcghg0",
        parent: "0",
        label: "菜单大类",
        value: "menuCategory",
        createdAt: "2024-01-28 11:44:58",
        updatedAt: null,
        remark: "路由菜单，目录菜单等",
        children: [
          {
            dictId: "cmqsrqbdervjk5pcghh0",
            parent: "cmqsrejdervjk5pcghg0",
            label: "文档",
            value: "note",
            createdAt: "2024-01-28 11:45:46",
            updatedAt: null,
            remark: "文档菜单",
            children: null,
          },
          {
            dictId: "cmqsrl3dervjk5pcghgg",
            parent: "cmqsrejdervjk5pcghg0",
            label: "路由",
            value: "routes",
            createdAt: "2024-01-28 11:45:25",
            updatedAt: null,
            remark: "路由菜单",
            children: null,
          },
        ],
      },
      {
        dictId: "cmv4vq3dervirktgq5n0",
        parent: "0",
        label: "test1123",
        value: "test1123",
        createdAt: "2024-02-03 22:38:33",
        updatedAt: "2024-02-03 22:38:40",
        remark: "test1123",
        children: [
          {
            dictId: "cmv50qjdervirktgq5ng",
            parent: "cmv4vq3dervirktgq5n0",
            label: "qqq",
            value: "qqq",
            createdAt: "2024-02-03 22:40:42",
            updatedAt: "2024-02-03 22:42:12",
            remark: "qqq",
            children: null,
          },
        ],
      },
      {
        dictId: "cn08srbdervqmt7o7td0",
        parent: "0",
        label: "11",
        value: "1231",
        createdAt: "2024-02-05 15:29:50",
        updatedAt: null,
        remark: "23",
        children: null,
      },
      {
        dictId: "cmbc2j0mffl4191upm0g",
        parent: "0",
        label: "笔记分类",
        value: "noteCategory",
        createdAt: null,
        updatedAt: null,
        remark: "",
        children: [
          {
            dictId: "cmbc3ggmffl4191upm50",
            parent: "cmbc2j0mffl4191upm0g",
            label: "微信",
            value: "wechat",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc39omffl4191upm4g",
            parent: "cmbc2j0mffl4191upm0g",
            label: "linux",
            value: "linux",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc37omffl4191upm40",
            parent: "cmbc2j0mffl4191upm0g",
            label: "nginx",
            value: "nginx",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc368mffl4191upm3g",
            parent: "cmbc2j0mffl4191upm0g",
            label: "docker",
            value: "docker",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc30omffl4191upm30",
            parent: "cmbc2j0mffl4191upm0g",
            label: "node",
            value: "node",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc2t0mffl4191upm2g",
            parent: "cmbc2j0mffl4191upm0g",
            label: "golang",
            value: "golang",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc2rgmffl4191upm20",
            parent: "cmbc2j0mffl4191upm0g",
            label: "javascript",
            value: "javascript",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc2q0mffl4191upm1g",
            parent: "cmbc2j0mffl4191upm0g",
            label: "css",
            value: "css",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmbc2o0mffl4191upm10",
            parent: "cmbc2j0mffl4191upm0g",
            label: "html",
            value: "html",
            createdAt: null,
            updatedAt: null,
            remark: "",
            children: null,
          },
        ],
      },
      {
        dictId: "cmqsndg5lm7vlg415isg",
        parent: "0",
        label: "是否",
        value: "whether",
        createdAt: "2024-01-28 03:36:23",
        updatedAt: null,
        remark: "是否选项 true false",
        children: [
          {
            dictId: "cmqsns85lm7vlg415itg",
            parent: "cmqsndg5lm7vlg415isg",
            label: "否",
            value: "0",
            createdAt: "2024-01-28 03:37:22",
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmqsni05lm7vlg415it0",
            parent: "cmqsndg5lm7vlg415isg",
            label: "是",
            value: "1",
            createdAt: "2024-01-28 03:36:41",
            updatedAt: "2024-01-28 11:43:14",
            remark: "",
            children: null,
          },
        ],
      },
      {
        dictId: "cmqtdsrdervjk5pcghhg",
        parent: "0",
        label: "数据类型",
        value: "typeof",
        createdAt: "2024-01-28 12:24:20",
        updatedAt: null,
        remark: "javascript数据类型",
        children: [
          {
            dictId: "cmqtedrdervjk5pcghk0",
            parent: "cmqtdsrdervjk5pcghhg",
            label: "对象",
            value: "object",
            createdAt: "2024-01-28 12:25:28",
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmqtebbdervjk5pcghjg",
            parent: "cmqtdsrdervjk5pcghhg",
            label: "数组",
            value: "array",
            createdAt: "2024-01-28 12:25:18",
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmqte8jdervjk5pcghj0",
            parent: "cmqtdsrdervjk5pcghhg",
            label: "布尔",
            value: "boolean",
            createdAt: "2024-01-28 12:25:07",
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmqte53dervjk5pcghig",
            parent: "cmqtdsrdervjk5pcghhg",
            label: "数字",
            value: "number",
            createdAt: "2024-01-28 12:24:52",
            updatedAt: null,
            remark: "",
            children: null,
          },
          {
            dictId: "cmqte23dervjk5pcghi0",
            parent: "cmqtdsrdervjk5pcghhg",
            label: "字符串",
            value: "string",
            createdAt: "2024-01-28 12:24:41",
            updatedAt: null,
            remark: "",
            children: null,
          },
        ],
      },
    ],
  },
];
